export const FETCH_ALL_ANIMALS_PENDING = "FETCH_ALL_ANIMALS_PENDING";
export const FETCH_ALL_ANIMALS_SUCCESS = "FETCH_ALL_ANIMALS_SUCCESS";
export const FETCH_ALL_ANIMALS_FAILED = "FETCH_ALL_ANIMALS_FAILED";

export const FETCH_ONE_ANIMAL_PENDING = "FETCH_ONE_ANIMAL_PENDING";
export const FETCH_ONE_ANIMAL_SUCCESS = "FETCH_ONE_ANIMAL_SUCCESS";
export const FETCH_ONE_ANIMAL_FAILED = "FETCH_ONE_ANIMAL_FAILED";

export const ADD_ANIMAL_PENDING = "ADD_ANIMAL_PENDING";
export const ADD_ANIMAL_SUCCESS = "ADD_ANIMAL_SUCCESS";
export const ADD_ANIMAL_FAILED = "ADD_ANIMAL_FAILED";

export const REMOVE_ANIMAL_PENDING = "REMOVE_ANIMAL_PENDING";
export const REMOVE_ANIMAL_SUCCESS = "REMOVE_ANIMAL_SUCCESS";
export const REMOVE_ANIMAL_FAILED = "REMOVE_ANIMAL_FAILED";

export const EDIT_ANIMAL_SUCCESS = "EDIT_ANIMAL_SUCCESS";
export const EDIT_ANIMAL_FAILED = "EDIT_ANIMAL_FAILED";
export const EDIT_ANIMAL_PENDING = "EDIT_ANIMAL_PENDING";

export const BASE_URL = "http://localhost:8000/animals";
